### ISSUE TITLE
找不到可以getTextContainer的节点，请联系开发人员

### ISSUE THREAD

**Issue by 760682879** [BigCoal/js-mark#2]
renderStore 使用失效，找不到可以getTextContainer的节点，请联系开发人员,查看vTextNodes 发现只有一个数组

**Comment by BigCoal** [comment]
> renderStore 使用失效，找不到可以getTextContainer的节点，请联系开发人员,查看vTextNodes 发现只有一个数组

已经修复此bug，请拉取新的代码，或更新版本在1.0.6及以上版本
